made more flexible

diff --git a/sh/inst b/sh/inst
--- a/sh/inst
+++ b/sh/inst
@@ -1,18 +1,28 @@
 #!/bin/sh
-# 2013/12/02, sunsd
+# 2013/12/13, sunsd
 
 HTDOCS=$CCRUN/htdocs
 
-proj=$(pn)
-module="webframe"
-if [ $# -gt 0 ]; then
-    module=$1
+pwd=`pwd`
+pd=$(pd)
+[ $# -gt 0 ] && module=$1 || module=$MOD
+if [ "$module" = "" ]; then
+    echo "Warning: module was not specified!" >&2
+    if [[ $pwd = *ccsrc* ]]; then
+        guess_mod=`echo $pwd|cut -d/ -f5`
+        (ask "Do you mean this? $guess_mod")
+        [ $? -ne 0 ] && exit 1
+        module=$guess_mod
+    else
+        exit 1
+    fi
 fi
-makefile="/project/$proj/ccsrc/$module/Makefile"
+makefile="$pd/$module/Makefile"
 if [ -e $makefile ]; then
     INSTDIR=$(grep -m 1 "^INSTALLDIR" $makefile|cut -d= -f2|tr '()' '{}')
     INSTDIR=$(eval echo $INSTDIR)
     echo $INSTDIR
 else
-    echo "Error: module not found!"
+    echo "Error: module {$module} not found!" >&2
+    exit 1
 fi
diff --git a/sh/wp b/sh/wp
--- a/sh/wp
+++ b/sh/wp
@@ -2,18 +2,18 @@
 # 2013/12/02, sunsd
 
 f=$1
-module="webframe"
+pwd=`pwd`
+module=$MOD
 if [ "${f:0:1}" != "/" ]; then
-    f="`pwd`/$f"
+    f="$pwd/$f"
 fi
 if [[ "$f" = */$module* ]]; then
     INSTDIR=$(inst $module)
-    cmd=".dosu cp $f $INSTDIR/${f#*webframe/}"
+    [ $? -ne 0 ] && exit 1
+    cmd=".dosu cp $f $INSTDIR/${f#*$module/}"
     echo $cmd
     eval $cmd
-    if [ $? -eq 0 ]; then
-        echo "[7mDone.[0m"
-    fi
+    [ $? -eq 0 ] && echo "[7mDone.[0m"
 else
-    echo "Path is not valid!"
+    echo "Error: Path is not valid!" >&2
 fi
