fixed a bug of inst

diff --git a/sh/inst b/sh/inst
--- a/sh/inst
+++ b/sh/inst
@@ -10,12 +10,14 @@ pd=$(pd)
 if [ "$module" = "" ]; then
     echo "Warning: env MOD is null!" >&2
     if [[ $pwd = *ccsrc* ]]; then
-        guess_mod=`echo $pwd|cut -d/ -f5`
-        (confirm "Take { $guess_mod } as the module this time.")
+        n=5
+        [[ $pwd = /ccsrc* ]] && n=3
+        guess_mod=`echo $pwd|cut -d/ -f$n`
+        (confirm "Automatically set MOD = { $guess_mod }")
         [ $? -ne 0 ] && exit 1
         module=$guess_mod
     else
-        echo "Error: None possible value for MOD!" >&2
+        echo "Error: none possible value for MOD!" >&2
         exit 1
     fi
 fi
diff --git a/sh/pd b/sh/pd
--- a/sh/pd
+++ b/sh/pd
@@ -10,10 +10,10 @@ pdirname()
         if [[ $dir = /ccsrc* ]]; then
             dir=$(ct 2)
         elif [[ $dir != */ccsrc* ]]; then
-            echo "Error: None possible value for PROJ!" >&2
+            echo "Error: none possible value for PROJ!" >&2
             exit 1
         fi
-        echo "automatically set to PROJ=$dir" >&2
+        echo "Automatically set PROJ dir = { $dir }" >&2
     fi
     echo $dir
 }
